/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package experienciausuario;

import MetodosSQL.MetodosSQL;
import static MetodosSQL.MetodosSQL.BuscarCorreo;
import javax.swing.ImageIcon;
//import PDF.plantilla;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

import MetodosSQL.MetodosSQL;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.Properties;
import javax.swing.Icon;
import javax.swing.JButton;

/**
 *
 * @author javie
 */

public class FrmModulos extends javax.swing.JFrame {

    
    String nombre;
    String correoMio ;
    String contrasenaMio;
    String correoDestino;
    Document documento;
    FileOutputStream archivo;
    Paragraph titulo;

    public FrmModulos(java.awt.Frame parent, boolean modal) {
        initComponents();
        
        setLocationRelativeTo(null);
        JLImagen1.setVisible(false);
        JLImagen2.setVisible(false);
        JLImagen3.setVisible(false);
        JLImagen4.setVisible(false);
        JLImagen5.setVisible(false);
        rsscalelabel.RSScaleLabel.setScaleLabel(JLImagen0, "src/imagenes/Modulo5.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLAzul, "src/imagenes/UXx.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLImagen0, "src/imagenes/Imagenuxui.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLImagen1, "src/imagenes/modulo1.jpeg");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLImagen2, "src/imagenes/modulo2.jpeg");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLImagen3, "src/imagenes/modulo3.jpeg");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLImagen4, "src/imagenes/modulo4.jpeg");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLImagen5, "src/imagenes/modulo5.png");

      

       /* jButton1.setContentAreaFilled(false);
        jButton2.setContentAreaFilled(false);
        jButton3.setContentAreaFilled(false);
        jButton4.setContentAreaFilled(false);*/

        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        JBFinModulos.setEnabled(false);
        //jButton1.addActionListener(null);
    
    }
    MetodosSQL metodos = new MetodosSQL();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelContenedor = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        JBFinModulos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LbUser = new javax.swing.JLabel();
        LbUser1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        JLAzul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        JLImagen0 = new javax.swing.JLabel();
        JLImagen1 = new javax.swing.JLabel();
        JLImagen2 = new javax.swing.JLabel();
        JLImagen3 = new javax.swing.JLabel();
        JLImagen4 = new javax.swing.JLabel();
        JLImagen5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        JLNotaModulo1 = new javax.swing.JLabel();
        JLNotaMidulo2 = new javax.swing.JLabel();
        JLNotaMidulo3 = new javax.swing.JLabel();
        JLNotaMidulo4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelContenedor.setBackground(new java.awt.Color(153, 255, 255));
        JPanelContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 4));
        JPanelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mod44.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 4));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        JPanelContenedor.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 310, 210));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mod22.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 4));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        JPanelContenedor.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 310, 210));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mod33.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 4));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        JPanelContenedor.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 310, 210));

        JBFinModulos.setText("Finzalizar modulos ");
        JBFinModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBFinModulosActionPerformed(evt);
            }
        });
        JPanelContenedor.add(JBFinModulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, 150, 50));

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        JPanelContenedor.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 20, 700));

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbUser.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(LbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 30, 280, 30));

        LbUser1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbUser1.setForeground(new java.awt.Color(255, 255, 255));
        LbUser1.setText("BIENVENIDO(A) A NUESTROS MODULOS");
        jPanel2.add(LbUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 370, 30));

        JPanelContenedor.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 750, 100));

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLAzul.setBackground(new java.awt.Color(153, 0, 153));
        JLAzul.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLAzul.setText("1");
        jPanel4.add(JLAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 190, 100));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Rebelion X Digital");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 190, 30));

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 370, 40));

        jLabel2.setText("jLabel2");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        JPanelContenedor.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 370, 170));

        jTabbedPane1.addTab("tab1", JLImagen0);

        JLImagen1.setText("jLabel3");
        jTabbedPane1.addTab("tab2", JLImagen1);

        JLImagen2.setText("jLabel4");
        jTabbedPane1.addTab("tab3", JLImagen2);

        JLImagen3.setText("jLabel5");
        jTabbedPane1.addTab("tab4", JLImagen3);

        JLImagen4.setText("jLabel6");
        jTabbedPane1.addTab("tab5", JLImagen4);

        JLImagen5.setText("jLabel7");
        jTabbedPane1.addTab("tab6", JLImagen5);

        JPanelContenedor.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 370, 320));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mod11.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 4));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        JPanelContenedor.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, 210));

        JLNotaModulo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLNotaModulo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPanelContenedor.add(JLNotaModulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 30, 30));

        JLNotaMidulo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLNotaMidulo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPanelContenedor.add(JLNotaMidulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 30, 30));

        JLNotaMidulo3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLNotaMidulo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPanelContenedor.add(JLNotaMidulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 30, 30));

        JLNotaMidulo4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLNotaMidulo4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPanelContenedor.add(JLNotaMidulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 30, 30));

        jPanel5.setBackground(new java.awt.Color(0, 51, 153));
        JPanelContenedor.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, 370, 40));

        getContentPane().add(JPanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBFinModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBFinModulosActionPerformed


        /*String Busca_Nombre = metodos.BuscarNombre(LbUser.getText());

       documento = new Document(PageSize.A4.rotate());
       // titulo = new Paragraph("Felicidades");

        try {
            File file = new File("src/PDF/CERTIFICADO.pdf");
            archivo = new FileOutputStream(file);
            //PdfWriter.getInstance(documento, archivo);
            documento.open();
            documento.add(new Paragraph("nombre: " + Busca_Nombre));/*
            titulo.setAlignment(1);
            documento.add(titulo);
            //documento.add(new Paragraph(MetodosSQL.BuscarNombre(nombre)));
            //documento.add(new Paragraph(MetodosSQL.BuscarNombre(apellido)));
            
            //documento.add(new Paragraph("apellido:"+Buscar_Nombre));
            documento.add(Chunk.NEWLINE);

            Paragraph texto = new Paragraph("El término UX viene de User Experience, o Experiencia del Usuario. Básicamente es cómo una persona se siente mientras usa cualquier producto o servicio digital que tu empresa ofrece.\n"
                    + "\n"
                    + "UX tiene que ver también con la sensación de esta persona después de usar tu producto.\n"
                    + "\n"
                    + "Eso incluye su experiencia con tu sitio web y blog, el sistema online o la aplicación, incluso, si tu negocio no es 100% digital también aplica.");

            texto.setAlignment(Element.ALIGN_JUSTIFIED);
            documento.add(texto);
            documento.add(Chunk.NEWLINE);
            //documento.add(new Paragraph("fecha:"+fecha));
            documento.close();
        } catch (FileNotFoundException | DocumentException e) {
            System.err.println(e.getMessage());
        }*/
        
        EnviarCorreo ve = new EnviarCorreo();
        EnviarCorreo.JLResiveCorreo.setText(BuscarCorreo(LbUser.getText()));
        ve.setVisible(true);
        
   
    }//GEN-LAST:event_JBFinModulosActionPerformed

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        JLImagen4.setVisible(false);
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        JLImagen4.setVisible(true);
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        JLImagen3.setVisible(false);
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        JLImagen3.setVisible(true);
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if (JLNotaMidulo2.getText().equals("7") || JLNotaMidulo2.getText().equals("8") || JLNotaMidulo2.getText().equals("9") || JLNotaMidulo2.getText().equals("10")) {

            JOptionPane.showMessageDialog(null, "Ya superaste es modulo continua con el siguiente");

        } else {
            JOptionPane.showMessageDialog(null, "cargando videos espere");
            FrmVideo2 video = new FrmVideo2();
           // FrmVideo.jTabbedPane2.setSelectedIndex(1);
            FrmVideo2.JLNotaM1.setText(JLNotaModulo1.getText());
            FrmVideo2.JLUsuario.setText(LbUser.getText());
            video.setVisible(true);

            this.dispose();

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        JLImagen2.setVisible(false);
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        JLImagen2.setVisible(true);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (JLNotaModulo1.getText().equals("7") || JLNotaModulo1.getText().equals("8") || JLNotaModulo1.getText().equals("9") || JLNotaModulo1.getText().equals("10")) {

            JOptionPane.showMessageDialog(null, "Ya superaste es modulo continua con el siguiente");

        } else {
            JOptionPane.showMessageDialog(null, "cargando videos espere");
            FrmVideo v = new FrmVideo();
            v.setVisible(true);
            FrmVideo.JLUsuario.setText(LbUser.getText());

            this.dispose();

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        JLImagen1.setVisible(true);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        JLImagen1.setVisible(false);
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (JLNotaMidulo3.getText().equals("7") || JLNotaMidulo3.getText().equals("8") || JLNotaMidulo3.getText().equals("9") || JLNotaMidulo3.getText().equals("10")) {

            JOptionPane.showMessageDialog(null, "Ya superaste es modulo continua con el siguiente");

        } else {
            JOptionPane.showMessageDialog(null, "cargando videos espere");
            FrmVideo3 ventana = new FrmVideo3();
            ventana.setVisible(true);
            //FrmVideo1.jTabbedPane2.setSelectedIndex(2);
            FrmVideo3.JLNotaM1.setText(JLNotaModulo1.getText());
            FrmVideo3.JLNotaM2.setText(JLNotaMidulo2.getText());
            FrmVideo3.JLUsuario.setText(LbUser.getText());

            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (JLNotaMidulo4.getText().equals("7") || JLNotaMidulo4.getText().equals("8") || JLNotaMidulo4.getText().equals("9") || JLNotaMidulo4.getText().equals("10")) {

            JOptionPane.showMessageDialog(null, "Ya terminaste todos los modulos aplasta finalizar");

        } else {
            JOptionPane.showMessageDialog(null, "cargando videos espere");
            FrmVideo4 ventana = new FrmVideo4();
            ventana.setVisible(true);
            //FrmVideo4.jTabbedPane2.setSelectedIndex(3);
            FrmVideo4.JLNotaM1.setText(JLNotaModulo1.getText());
            FrmVideo4.JLNotaM2.setText(JLNotaMidulo2.getText());
            FrmVideo4.JLNotaM3.setText(JLNotaMidulo2.getText());
            FrmVideo4.JLUsuario.setText(LbUser.getText());
            

            this.dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               FrmModulos dialog = new FrmModulos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public final Icon setIcon(String url, JButton boton) {

        ImageIcon icon = new ImageIcon(getClass().getResource(url));

        int ancho = boton.getWidth();
        int alto = boton.getHeight();

        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));

        return icono;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton JBFinModulos;
    private javax.swing.JLabel JLAzul;
    private javax.swing.JLabel JLImagen0;
    private javax.swing.JLabel JLImagen1;
    private javax.swing.JLabel JLImagen2;
    private javax.swing.JLabel JLImagen3;
    private javax.swing.JLabel JLImagen4;
    private javax.swing.JLabel JLImagen5;
    public static javax.swing.JLabel JLNotaMidulo2;
    public static javax.swing.JLabel JLNotaMidulo3;
    public static javax.swing.JLabel JLNotaMidulo4;
    public static javax.swing.JLabel JLNotaModulo1;
    private javax.swing.JPanel JPanelContenedor;
    public static javax.swing.JLabel LbUser;
    public static javax.swing.JLabel LbUser1;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
