/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package experienciausuario;

import MetodosSQL.MetodosSQL;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author javie
 */
public class FrmRegistroUsuario extends javax.swing.JFrame {

     
    /**
     * Creates new form FrmRegistroUsuario
     * @param parent
     * @param modal
     */
    public FrmRegistroUsuario(java.awt.Frame parent, boolean modal) {
       //super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        JlCorreo.setVisible(false);
        BtGuardar.setEnabled(false);
       //BtRegresar.setIcon(setIcon("/Imagenes/regresar_1.png", BtRegresar));
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel1,"src/imagenes/U.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLRegresar,"src/imagenes/regresar_1.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(JLGuardar,"src/imagenes/Guardar_1.png");
        
        
    }
        MetodosSQL metodos = new MetodosSQL(); 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        BtGuardar = new javax.swing.JButton();
        BtRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JlCorreo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JLRegresar = new javax.swing.JLabel();
        JLGuardar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 4, true));
        jPanel2.setForeground(new java.awt.Color(0, 51, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtGuardar.setBackground(new java.awt.Color(0, 51, 153));
        BtGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtGuardar.setText("Guardar ");
        BtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(BtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 100, 30));

        BtRegresar.setBackground(new java.awt.Color(0, 51, 153));
        BtRegresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtRegresar.setForeground(new java.awt.Color(255, 255, 255));
        BtRegresar.setText("Regresar");
        BtRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(BtRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 100, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Apellido");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 179, -1, -1));

        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });
        jPanel2.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 174, 160, 25));

        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 129, 160, 25));

        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 219, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Correo");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 222, -1, -1));

        JlCorreo.setText("correo invalido");
        JlCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JlCorreoFocusLost(evt);
            }
        });
        jPanel2.add(JlCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 222, 96, -1));
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 259, 160, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Usuario");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 263, -1, 15));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Contraseña");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 304, -1, 27));

        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });
        jPanel2.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 304, 160, 27));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 134, -1, -1));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 80, 60));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Registro de usuarios");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));
        jPanel2.add(JLRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 20, 20));
        jPanel2.add(JLGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 50, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        if(metodos.verificar_Email(txtCorreo.getText())){

            JlCorreo.setVisible(false);
            BtGuardar.setEnabled(true);

        }else{
            JlCorreo.setVisible(true);
            BtGuardar.setEnabled(false);
        }

    }//GEN-LAST:event_txtCorreoFocusLost

    private void JlCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JlCorreoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_JlCorreoFocusLost

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        char c = evt.getKeyChar();

        if((c<'a'|| c> 'z') && (c<'A' )| c>'Z')evt.consume();
        //Toolkit.getDefaultToolkit().beep();
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void BtRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRegresarActionPerformed
        FrmLogin ventana = new FrmLogin();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtRegresarActionPerformed

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        char c = evt.getKeyChar();

        if((c<'a'|| c> 'z') && (c<'A' )| c>'Z')evt.consume();
        //Toolkit.getDefaultToolkit().beep();
    }//GEN-LAST:event_txtNombresKeyTyped

    private void BtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGuardarActionPerformed

        boolean nombre = metodos.ValidarLetras(txtNombres.getText());
        boolean apellido = metodos.ValidarLetras(txtApellidos.getText());

        if (txtNombres.getText().equals("") || txtApellidos.getText().equals("") || txtCorreo.getText().equals("") || txtUsuario.getText().equals("") || String.valueOf(txtContrasena.getPassword()).equals("") ){
            JOptionPane.showMessageDialog(null, "Faltan campos por llenar ");
        }else{
            if (metodos.ValidarUsuarioRepetido(txtUsuario.getText())==0 ){

                metodos.guardar(txtNombres.getText(),txtApellidos.getText(), txtCorreo.getText(), txtUsuario.getText(), String.valueOf(txtContrasena.getPassword()));
                JOptionPane.showMessageDialog(null, "guardado ");

            } else{
                JOptionPane.showMessageDialog(null, "el usuario ya existe ");
            }
        }

    }//GEN-LAST:event_BtGuardarActionPerformed

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRegistroUsuario dialog = new FrmRegistroUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public Icon setIcon(String url, JButton boton){
    
        ImageIcon icon = new ImageIcon( getClass().getResource(url));
        
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho,alto,Image.SCALE_DEFAULT));
        
        return icono;
      
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtGuardar;
    private javax.swing.JButton BtRegresar;
    private javax.swing.JLabel JLGuardar;
    private javax.swing.JLabel JLRegresar;
    private javax.swing.JLabel JlCorreo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    





}